rust_library(
    name = "kernel-lib",
    srcs = glob(["**/*.rs"], exclude = ["main.rs"]) + ["ramdisk.fat32.zst"],
    crate = "kernel",
    crate_root = "lib.rs",
    default_target_platform = "root//platforms:kernel-aarch64",
    edition = "2024",
    deps = [
        "//src/vfs:vfs",
        "deps//rust:aarch64-cpu",
        "deps//rust:aarch64-paging",
        "deps//rust:arm-gic",
        "deps//rust:lz4rip",
        "deps//rust:object",
        "deps//rust:safe-mmio",
        "deps//rust:spin",
        "deps//rust:virtio-drivers",
        "deps//rust:zrip",
    ],
    visibility = ["PUBLIC"],
)

export_file(
    name = "linker_script",
    src = "boot/linker.ld",
    visibility = ["PUBLIC"],
)

export_file(
    name = "linker_script_meson",
    src = "boot/linker-meson.ld",
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "kernel",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    default_target_platform = "root//platforms:kernel-aarch64",
    edition = "2024",
    linker_flags = [
        "-Wl,-T,$(location :linker_script)",
    ],
    deps = [
        ":kernel-lib",
        "//src/loader:loader",
        "//src/vfs:vfs",
    ],
    visibility = ["PUBLIC"],
)

rust_binary(
    name = "kernel-meson",
    srcs = ["main.rs"],
    crate_root = "main.rs",
    default_target_platform = "root//platforms:kernel-aarch64",
    edition = "2024",
    linker_flags = [
        "-Wl,-T,$(location :linker_script_meson)",
    ],
    deps = [
        ":kernel-lib",
        "//src/loader:loader",
        "//src/vfs:vfs",
    ],
    visibility = ["PUBLIC"],
)
