[workspace]
resolver = "3"
members = [
  "metalc/metallib",
  "metalc/air-bitcode",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/opendarwin/src"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
sha2 = "0.11"
rustc-hash = "2"

metallib = { path = "crates/metallib" }
air-bitcode = { path = "crates/air-bitcode" }
