[workspace]
resolver = "3"
members = [
  "src/kernel",
  "src/libsystem",
  "src/iokit",
  "src/metalc/metallib",
  "src/metalc/air-bitcode",
  "src/metalc/dialect-metal",
  "src/metalc/dialect-air",
  "src/metalc/metal-transforms",
  "src/metalc/metal-lower",
  "src/metalc/msl-frontend",
  "src/metalc/metalc",
  "src/metalc/metalc-host-test",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/opendarwin-project/src"

[workspace.dependencies]
pliron = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074" }
pliron-derive = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074" }
pliron-llvm = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074", default-features = false, features = ["std"] }
anyhow = "1"
annotate-snippets = "0.12"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
sha2 = "0.11"
rustc-hash = "2"
spin = "0.12.2"
lz4rip = { version = "0.11.3", default-features = false, features = ["alloc"] }
safe-mmio = "0.3.1"
x86_64 = "0.15.5"
arm-gic = "0.9.0"
aarch64-cpu = "11.2.0"
aarch64-paging = "0.12.1"
virtio-drivers = "0.13.0"
object = { version = "0.40.0", default-features = false, features = ["read_core", "macho", "elf"] }
hadris-fat = { version = "2.0.0", default-features = false }
hadris-io = { version = "2.0.0", default-features = false }

metallib = { path = "metalc/metallib" }
air-bitcode = { path = "metalc/air-bitcode" }
dialect-metal = { path = "metalc/dialect-metal" }
dialect-air = { path = "metalc/dialect-air" }
metal-transforms = { path = "metalc/metal-transforms" }
metal-lower = { path = "metalc/metal-lower" }
msl-frontend = { path = "metalc/msl-frontend" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = "thin"

[profile.dev]
panic = "abort"

[workspace.lints.clippy]
too_many_arguments = "allow"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
