[workspace]
resolver = "3"
members = [
  "src/libsystem",
  "src/iokit",
  "metalc/metallib",
  "metalc/air-bitcode",
  "metalc/dialect-metal",
  "metalc/dialect-air",
  "metalc/metal-transforms",
  "metalc/metal-lower",
  "metalc/msl-frontend",
  "metalc/metalc",
  "metalc/metalc-host-test",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/opendarwin/src"

[workspace.dependencies]
pliron = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074" }
pliron-derive = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074" }
pliron-llvm = { git = "https://github.com/pliron-org/pliron", rev = "a2ca8f0f6aa73df049f651e9021ab70100646074", default-features = false, features = ["std"] }
anyhow = "1"
annotate-snippets = "0.12"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
sha2 = "0.11"
rustc-hash = "2"
spin = "0.12.2"

metallib = { path = "metalc/metallib" }
air-bitcode = { path = "metalc/air-bitcode" }
dialect-metal = { path = "metalc/dialect-metal" }
dialect-air = { path = "metalc/dialect-air" }
metal-transforms = { path = "metalc/metal-transforms" }
metal-lower = { path = "metalc/metal-lower" }
msl-frontend = { path = "metalc/msl-frontend" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = "thin"

[profile.dev]
panic = "abort"

[workspace.lints.clippy]
too_many_arguments = "allow"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
