load(":cxx_tools.bzl", "opendarwin_cxx_toolchain")
load(":local_demo.bzl", "local_demo_toolchains")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

local_demo_toolchains()

genrule(
    name = "libsystem-stub-dir",
    out = "lib",
    cmd = "mkdir -p $OUT && llvm-ar rcs $OUT/libSystem.a",
)

opendarwin_cxx_toolchain(
    name = "cxx",
    linker = select({
        "root//platforms:kernel": "clang",
        "DEFAULT": "clang++",
    }),
    linker_type = select({
        "root//platforms:kernel": "gnu",
        "prelude//os/constraints:macos": "darwin",
        "DEFAULT": "gnu",
    }),
    link_flags = select({
        "root//platforms:kernel": [
            "--target=aarch64-unknown-none-elf",
            "-nostdlib",
            "-nostartfiles",
        ],
        "prelude//os/constraints:macos": [
            "-fuse-ld=lld",
            "-L$(location :libsystem-stub-dir)",
        ],
        "DEFAULT": [],
    }),
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    default_edition = "2024",
    rustc_flags = select({
        "root//platforms:kernel": [
            "-Copt-level=s",
            "-Cpanic=abort",
            "-Cforce-frame-pointers=yes",
            "-Zunstable-options",
            "-Clinker-flavor=gcc",
            "-Clink-arg=-nodefaultlibs",
            "-Clink-arg=-nostdlib",
        ],
        "prelude//os/constraints:macos": ["-Cpanic=abort", "-Csplit-debuginfo=unpacked", "-Copt-level=2"],
        "DEFAULT": ["-Copt-level=2"],
    }),
    rustc_target_triple = select({
        "root//platforms:kernel": "aarch64-unknown-none",
        "DEFAULT": None,
    }),
    visibility = ["PUBLIC"],
)
