rust_library(
    name = "air-bitcode",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/metalc/metallib:metallib",
        "deps//rust:anyhow",
        "deps//rust:sha2",
        "deps//rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)
