rust_library(
    name = "metal-lower",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/metalc/air-bitcode:air-bitcode",
        "//src/metalc/dialect-air:dialect-air",
        "//src/metalc/dialect-metal:dialect-metal",
        "deps//rust:pliron",
        "deps//rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)
