rust_binary(
    name = "mkramdisk",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        "deps//rust:lz4rip",
    ],
    visibility = ["PUBLIC"],
)
