rust_binary(
    name = "amlogic-boot",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        "deps//rust:anyhow",
        "deps//rust:clap",
    ],
    visibility = ["PUBLIC"],
)
