#!/usr/bin/env bash
# Generated by qemu_boot (tools/qemu/qemu_boot.bzl) - boots
# {{KERNEL_RLOCATIONPATH}} under a hermetic qemu-system-aarch64 `virt`
# machine.
#
# Usage: bazel run //tools/qemu:kernel -- [-d ROOTFS_IMG] [-g] [-- QEMU_ARGS...]
#   -d ROOTFS_IMG  attach ROOTFS_IMG as a virtio-blk-device (mmio) drive;
#                  see tools/make_fat32.py for building one. Without this,
#                  the kernel boots but reports "no virtio-blk device found"
#                  and skips mounting a rootfs.
#   -g             also attach a virtio-gpu-pci device (needs a PCIe ECAM,
#                  which QEMU's virt machine provides automatically once any
#                  PCI device is present).
#   --             everything after this is passed through to
#                  qemu-system-aarch64 verbatim (e.g. `-d int,guest_errors`
#                  for debugging).
#
# The kernel's boot/linker.ld places entry at KERNEL_LOAD_ADDR (0x40080000),
# 0x80000 above virt's RAM base (0x40000000). QEMU doesn't hand a DTB
# pointer via x0 for an ELF passed to -kernel (only the raw Linux "Image"
# boot protocol gets that) and, as of QEMU 11.x, doesn't auto-generate one
# in RAM for ELF boot either - confirmed empirically, so this script dumps
# virt's DTB itself and loads it explicitly via `-device loader` right past
# the kernel's own 6MB reservation (devicetree.rs's fallback address, kept
# in sync with mmu::KERNEL_LOAD_ADDR + mmu::KERNEL_IMAGE_MAX_LEN below).
# GICv2 (drivers/gic.rs) and PSCI CPU_ON via HVC (drivers/psci.rs, smp.rs)
# match virt's defaults, so no extra -M options are needed for those.
# The hermetic qemu-system-aarch64 binary looks up its default ROM images
# (e.g. efi-virtio.rom, used by virt's PCIe option-ROM machinery even
# without an explicit -bios) relative to `-L`; point it at rules_qemu's
# "share/qemu" data directory so this works without a system QEMU install.
set -euo pipefail

# --- begin runfiles.bash initialization v3 ---
if [[ ! -d "${RUNFILES_DIR:-/dev/null}" && ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
  if [[ -f "$0.runfiles_manifest" ]]; then
    export RUNFILES_MANIFEST_FILE="$0.runfiles_manifest"
  elif [[ -f "$0.runfiles/MANIFEST" ]]; then
    export RUNFILES_MANIFEST_FILE="$0.runfiles/MANIFEST"
  elif [[ -f "$0.runfiles/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
    export RUNFILES_DIR="$0.runfiles"
  fi
fi
if [[ -f "${RUNFILES_DIR:-/dev/null}/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
  source "${RUNFILES_DIR}/bazel_tools/tools/bash/runfiles/runfiles.bash"
elif [[ -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
  source "$(grep -m1 "^bazel_tools/tools/bash/runfiles/runfiles.bash " \
            "$RUNFILES_MANIFEST_FILE" | cut -d ' ' -f2-)"
else
  echo >&2 "ERROR: cannot find @bazel_tools//tools/bash/runfiles:runfiles.bash"
  exit 1
fi
# --- end runfiles.bash initialization v3 ---

qemu_system="$(rlocation {{QEMU_SYSTEM_RLOCATIONPATH}})"
qemu_data_dir="$(rlocation {{QEMU_DATA_DIR_RLOCATIONPATH}})"
kernel="$(rlocation {{KERNEL_RLOCATIONPATH}})"
dtb_addr="{{DTB_ADDR}}"

rootfs_img=""
attach_gpu=0
while getopts "d:g" opt; do
    case "$opt" in
        d) rootfs_img="$OPTARG" ;;
        g) attach_gpu=1 ;;
        *)
            echo "usage: $0 [-d ROOTFS_IMG] [-g] [-- QEMU_ARGS...]" >&2
            exit 2
            ;;
    esac
done
shift $((OPTIND - 1))
if [ "${1:-}" = "--" ]; then
    shift
fi

machine_args=(-cpu max -smp 4 -m 512M)

dtb="$(mktemp -t opendarwin-virt-XXXXXX.dtb)"
trap 'rm -f "$dtb"' EXIT
"$qemu_system" -M "virt,dumpdtb=$dtb" -L "$qemu_data_dir" "${machine_args[@]}" -nographic >/dev/null 2>&1

qemu_args=(
    -M virt
    -L "$qemu_data_dir"
    "${machine_args[@]}"
    -nographic
    -kernel "$kernel"
    -device "loader,file=$dtb,addr=$dtb_addr,force-raw=on"
)

if [ -n "$rootfs_img" ]; then
    qemu_args+=(
        -drive "if=none,format=raw,file=$rootfs_img,id=hd0"
        -device virtio-blk-device,drive=hd0
    )
fi

if [ "$attach_gpu" -eq 1 ]; then
    qemu_args+=(-device virtio-gpu-pci)
fi

echo "==> $qemu_system ${qemu_args[*]} $*" >&2
exec "$qemu_system" "${qemu_args[@]}" "$@"
