rust_library(
    name = "loader",
    srcs = glob(["src/**/*.rs"]),
    crate = "loader",
    crate_root = "src/lib.rs",
    default_target_platform = "root//platforms:kernel-aarch64",
    edition = "2024",
    deps = [
        "//src/kernel:kernel-lib",
        "//src/vfs:vfs",
        "deps//rust:object",
        "deps//rust:spin",
    ],
    visibility = ["PUBLIC"],
)
