rust_library(
    name = "dialect-air",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/metalc/air-bitcode:air-bitcode",
        "deps//rust:pliron",
        "deps//rust:pliron-derive",
    ],
    visibility = ["PUBLIC"],
)
