rust_binary(
    name = "metalc",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    edition = "2024",
    deps = [
        "//src/metalc/air-bitcode:air-bitcode",
        "//src/metalc/dialect-air:dialect-air",
        "//src/metalc/dialect-metal:dialect-metal",
        "//src/metalc/metal-lower:metal-lower",
        "//src/metalc/metal-transforms:metal-transforms",
        "//src/metalc/metallib:metallib",
        "//src/metalc/msl-frontend:msl-frontend",
        "deps//rust:anyhow",
        "deps//rust:clap",
        "deps//rust:pliron",
    ],
    visibility = ["PUBLIC"],
)
