rust_library(
    name = "vfs",
    srcs = glob(["src/**/*.rs"]),
    crate = "vfs",
    crate_root = "src/lib.rs",
    default_target_platform = "root//platforms:kernel-aarch64",
    edition = "2024",
    deps = [
        "deps//rust:spin",
    ],
    visibility = ["PUBLIC"],
)
