rust_library(
    name = "metal-transforms",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//src/metalc/dialect-metal:dialect-metal",
        "deps//rust:pliron",
    ],
    visibility = ["PUBLIC"],
)
