rust_library(
    name = "metallib",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "deps//rust:sha2",
        "deps//rust:thiserror",
    ],
    visibility = ["PUBLIC"],
)
