name: Matrix Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      # TODO: replace with upstream repos in build.zig.zon
      - name: Checkout Prism
        uses: actions/checkout@v6
        with:
          repository: theoparis/prism
          path: deps/prism
      - name: Checkout Conduit
        uses: actions/checkout@v6
        with:
          repository: theoparis/conduit
          path: deps/conduit

      - name: Setup Zig
        uses: xyzzylabs/setup-zig@v1
        with:
          cache-key: ubuntu-latest-debug

      - name: Build and Test
        run: zig build
