name: CI

on:
    push:
        branches:
            - dev
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: macos-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Magic Nix Cache
              uses: DeterminateSystems/magic-nix-cache-action@main
              with:
                  use_flakehub: false
            - name: Run Nix Flake Check
              run: nix flake check --accept-flake-config --fallback
